### ISSUE TITLE
Create a way to print console.log in smart contracts

### ISSUE THREAD

**Issue by RomanHiden** [eth-brownie/brownie#792] opened 2020-10-05 07:46 UTC
### Overview
Smart contracts are hard to debug. This feature would allow printing console.log messages. Currently the only way to debug transactions is thru tx.call_trace() and tx.subcalls

### Specification
inlucde EVM that does allow printing console.log. 
https://buidler.dev/buidler-evm/

```
pragma solidity >=0.4.25 <0.7.0;

 import "./ConvertLib.sol";
+import "@nomiclabs/buidler/console.sol";

...

    function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
+       console.log(msg.sender, receiver, amount);
        if (balances[msg.sender] < amount) return false;
```

### Dependencies
 @nomiclabs

**Comment by iamdefinitelyahuman** [comment] 2020-10-06 18:35
Closing as a duplicate of #480 

I'm definitely into this idea, it's just a big job and haven't found the bandwidth for it yet.

**Closed by iamdefinitelyahuman** 2020-10-06 18:35 UTC
