### ISSUE TITLE
Scripts should allow args from cmd line

### ISSUE THREAD

**Issue by poolpitako** [eth-brownie/brownie#968] opened 2021-02-18 15:31 UTC
### Overview
Brownie should support args for running scripts.

* What you are trying to do
I am running scripts and I would like to pass arguments to the functions.

### Specification
@iamdefinitelyahuman happy to use whatever you prefer.
The most naive implementation I can think of is:
```
--args arg1,arg2,arg3
```

### Dependencies
None

**Comment by iamdefinitelyahuman** [comment] 2021-02-18 23:52
Duplicate of #398, some work toward this has been done in #816 and #930

**Closed by iamdefinitelyahuman** 2021-02-18 23:52 UTC
