### ISSUE TITLE
Unable publish source code with solidity version >= 0.8.0

### ISSUE THREAD

**Issue by maxsiz** [eth-brownie/brownie#1114] opened 2021-06-16 10:16 UTC
### Environment information

* `brownie` Version: 1.14.6
* `ganache-cli` Version: 0.8.4
* `solc` Version: 0.8.4
* Python Version: 3.6.9
* OS: linux

### What was wrong?
Every time when I try publish multifile source on Etherscan with sol version more then 0.8.0 error is occur.
```
Verification complete. Result: Fail - Unable to verify
```
But when i just change solidity version in pragma - all is  ok.  

I have check in console 
`First.get_verification_info()`  -  So in case sol >= 0.8.0 function return only  
first file in sources. 

At the same time, the deployment goes well in both cases.

Example sources are below.

### File 1 (First.sol)
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.4;
import "./Second.sol";
contract First is Second {
    function name() public view  returns (address) {
        return address(this);
    } 
    function symbol() public view  returns (string memory) {
        return "SYM";
    }
}
```
### File 2 (Second.sol)
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.4;
contract Second {
    function totalSupply() external view returns (uint256) {
        return 7777777777;
    }
}
```
### First.get_verification_info() output
```
>>> First.get_verification_info()
{
    'bytecode_len': 770,
    'compiler_version': "0.7.4+commit.3f05b770",
    'contract_name': "First",
    'flattened_source': "// SPDX-License-Identifier: MIT

pragma solidity 0.7.4;



// Part: Second

contract Second {
    function totalSupply() external view returns (uint256) {
        return 7777777777;
    }
}

// File: First.sol

contract First is Second {

    function name() public view  returns (address) {
        return address(this);
    }
    
    function symbol() public view  returns (string memory) {
        return "SYM";
    }
	
}
",
    'license_identifier': "MIT",
    'optimizer_enabled': True,
    'optimizer_runs': 200
}

```

### File 1 (First.sol)
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;
import "./Second.sol";
contract First is Second {
    function name() public view  returns (address) {
        return address(this);
    } 
    function symbol() public view  returns (string memory) {
        return "SYM";
    }
}
```
### File 2 (Second.sol)
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;
contract Second {
    function totalSupply() external view returns (uint256) {
        return 7777777777;
    }
}
```
### First.get_verification_info() output
```
Brownie environment is ready.
>>> First.get_verification_info()
{
    'bytecode_len': 602,
    'compiler_version': "0.8.4+commit.c7e474f2",
    'contract_name': "First",
    'flattened_source': "// SPDX-License-Identifier: MIT

pragma solidity 0.8.4;



// File: First.sol

contract First is Second {

    function name() public view  returns (address) {
        return address(this);
    }

    function symbol() public view  returns (string memory) {
        return "SYM";
    }
	
}
",
    'license_identifier': "MIT",
    'optimizer_enabled': True,
    'optimizer_runs': 200
}

```

**Comment by iamdefinitelyahuman** [comment] 2021-06-17 21:14
I think the issue is present from 0.8.4 onward.  Not sure what changed in that version, but something happened that broke everything.

**Comment by maxsiz** [comment] 2021-06-17 23:22
There are a lot of changes but code compiling is OK.  Only source collecting is broken
https://docs.soliditylang.org/en/breaking/080-breaking-changes.html

**Comment by gorillamania** [comment] 2021-06-23 01:35
I was able to use `pragma solidity 0.8.3;` and get it to work - so it's something with 0.8.4+

**Comment by PatrickAlphaC** [comment] 2021-07-11 00:29
It looks like it might have to do with `get_verification_info`. If I run `get_verification_info` on any contract with imports from OZ, it bugs out. Seems like it _should_ be pretty straightforward for one of us to fix.

**Comment by PatrickAlphaC** [comment] 2021-07-11 00:55
Yeah `get_verification_info` seems to be ignoring imports

**Comment by PatrickAlphaC** [comment] 2021-07-11 20:16
https://github.com/ethereum/solidity/issues/11643

I think this is the problem

**Comment by maxsiz** [comment] 2021-07-25 06:39
@iamdefinitelyahuman 
I have update brownie up to 1.15.1  but still  cant verify  code sol  version >= 0.8.0.   Does work in progress? May be you need some help?

**Comment by iamdefinitelyahuman** [comment] 2021-07-26 22:52
is this fixed in `v1.15.2` ?

**Comment by maxsiz** [comment] 2021-07-27 04:24
Thank you!
After `brownie compile --all`  seems that output `LockerByBlock.get_verification_info()
` look well.  I`ll check soon  on etherscan

**Comment by PatrickAlphaC** [comment] 2021-08-03 14:44
https://github.com/ethereum/solidity/issues/11643#issuecomment-891887826

Not sure if this conversation was addressed, haven't had a chance to jump into the brownie code yet.

**Closed** 2021-08-09 06:32 UTC
