### ISSUE TITLE
Publish code - Unable to verify

### ISSUE THREAD

**Issue by gnarvaja** [eth-brownie/brownie#1122] opened 2021-06-23 21:55 UTC
### Environment information

* `brownie` Version: v1.14.6
* `solc` Version: 0.8.6
* Python Version: 3.8.8
* OS: linux
* Network: kovan

### What was wrong?

```python
>>> tc = TestCurrency.at("0x9b4926E597CcC1867BbE7BB3b43cE66268ffD768")
>>> TestCurrency.publish_source(tc)
Verification submitted successfully. Waiting for result...
Verification pending...
Verification complete. Result: Fail - Unable to verify
False
```

TestCurrency.sol:

```solidity
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract TestCurrency is ERC20 {
  address private _owner;

  constructor(string memory name_, string memory symbol_, uint256 initialSupply) ERC20(name_, symbol_) {
    _owner = msg.sender;
    _mint(msg.sender, initialSupply);
  }

  function mint(address recipient, uint amount) public {
    // require(msg.sender == _owner, "Only owner can mint");
    return _mint(recipient, amount);
  }

  function burn(address recipient, uint amount) public {
    // require(msg.sender == _owner, "Only owner can burn");
    return _burn(recipient, amount);
  }

}
```

Also I tried verifying manually the .json in build folder and doesn't works either.

**Comment by iamdefinitelyahuman** [comment] 2021-06-23 23:13
Duplicate of #1076

**Closed by iamdefinitelyahuman** 2021-06-23 23:13 UTC
